version: "3.7"
services:
  web:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HubOS-Hotels
      MYSQL_USER: UbaldoSantos@HubOS
      MYSQL_PASSWORD: '6DIf0by8Kv*!'
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-php
    volumes:
      - ./src:/var/www/html/
    ports:
      - "9000:80"
    networks:
      - laravel

networks:
  laravel:

